version: 1

disable_existing_loggers: True
formatters:
  simple:
    format: "%(asctime)s %(name)-5s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  extended:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: log/log.log

loggers:
  __main__:
    level: INFO
    handlers: [console, file]
    propagate: False